// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Emotion Feedback",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Emotion Feedback",
            targets: ["AppModule"],
            bundleIdentifier: "io.github.picturehouse.EmotionFeedback",
            teamIdentifier: "WAC2RPX5HC",
            displayVersion: "1.0",
            bundleVersion: "3",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
